### ISSUE TITLE
EC2 Windows doesn't seem to work

### ISSUE THREAD

**Issue by stonith** [afiune/tk-windows#6]
Hi @afiune,

I can't seem to get ec2 working. I've used the following .kitchen.yml:

```

---
driver:
  name: ec2
  aws_access_key_id: ****
  aws_secret_access_key: *******
  security_group_ids: ["sg-*****"]
  region: us-west-2
  aws_ssh_key_id: kitchen-ci
  ssh_key: /tk-windows/id_rsa-aws
  flavor_id: m3.medium
  availability_zone: us-west-2b
  require_chef_omnibus: true

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
  - name: windows-2012R2
    driver:
      guest: :windows
      image_id: ami-21f0bc11

suites:
- name: default
  run_list:
    - 'recipe[tk-windows::default]'
  attributes:
```

But kitchen-ec2 seems to try to connect via SSH instead of WinRM.

```
> kitchen create default-windows-2012R2
-----> Starting Kitchen (v1.3.0)
-----> Creating <default-windows-2012R2>...
       EC2 instance <i-934d23df> created.
......       (server ready)
       Waiting for ec2-54-187-72-144.us-west-2.compute.amazonaws.com:22...
       Waiting for ec2-54-187-72-144.us-west-2.compute.amazonaws.com:22...
       Waiting for ec2-54-187-72-144.us-west-2.compute.amazonaws.com:22...
```

Your original AMI doesn't seem to be available anymore, is SSH preinstalled or is it a base image? I am using test-kitchen v1.3.0, kitchen-vagrant v0.16.0, and kitchen-ec2 v0.9.0.
